version: 0.0
os: linux
files:
  - source: /
    destination: /opt/tomcat8/webapps/
  
hooks:
  BeforeInstall:
    - location: agentstatus.sh
  #  - location: /opt/tomcat8/bin/startup.sh
      runas: root
