version: 0.0
os: linux
files:
  - source: /target/*.war
    destination: /opt/tomcat8/webapps
hooks:
  BeforeInstall:
    - location: service_status.sh
      runas: root
  AfterInstall:
    - location: codedeploy.sh
    - location: cleanup.sh    
