version: 0.0
os: linux
files:
  - source: /target/spring-mvc-showcase.war
    destination: /opt/tomcat8/webapps/
  - source: /target/spring-mvc-showcase
    destination: /opt/tomcat8/webapps/
hooks:
  BeforeInstall:
    - location: service_status.sh
      runas: root
     
